### ISSUE TITLE
performance issue with Kronecker product and complex values

### ISSUE THREAD

**Issue by vsaase** [Jutho/LinearMaps.jl#125]
Hi,
in this example I see a loss of efficiency for complex value:
```
using LinearAlgebra
using SparseArrays

spd = SparseMatrixCSC{ComplexF64}(I, 1000, 1000)
A = ones(2,2)
x = ones(2000)
B = kron(spd,A)
Bi = kron(spd, im*A)
Blm = kron(spd,LinearMap(A))
Blmi = kron(spd,im*LinearMap(A))

julia> @time B*x;
  0.000065 seconds (2 allocations: 31.328 KiB)
julia> @time Bi*x;
  0.000041 seconds (2 allocations: 31.328 KiB)
julia> @time Blm*x;
  0.000086 seconds (7 allocations: 47.266 KiB)
julia> @time Blmi*x;
  0.006984 seconds (1.01 k allocations: 187.969 KiB)

using Profile
@profile Blmi*x;
``` 
thanks for your work!,
Victor

**Comment by dkarrasch** [comment]
Thanks @vsaase for the report and the interesting benchmark problems. First of all, the issue is not about the complex factor `im` by itself: a real number would have resulted in the same slowdown. The issue is that, as was, we took the Kronecker product of a `WrappedMap` and a `ScaledMap`. That seems to complicate things further down the road, so the solution is to hoist out the scaling factor in Kronecker products. Note that any manipulation in `LinearMaps.jl` is lazy, so matrices or scaling factors are always taken as they are, and not silently promoted to something that some heuristic might guess is beneficial. This lets the user have full control (aka responsibility 😉 ).

I guess that much of your code above is just for a quick description of the issue, but in case some aspects of it are related to your work, let me comment and suggest a few improvements.

1. There is no need to convert the identity `I` to a sparse matrix, and thereby occupy 3 vectors of length 1000. You can replace this one by `LinearMap(I, 1000)`.
2. For matrices filled with a single value like your `A`, we have the `FillMap` type. It only stores the fill value and the size, nothing else.
3. Your case is a little special in that your `x` vector is real, but the matrices are complex. Since kron-vec-multiplication is implemented via the vec-trick, we call `mul!` potentially several times. When you have different eltypes, you may end up with the `generic_mat_vec_mul!`, which is of course slower than BLAS. So you may need to play a bit with the eltypes before you start with real big problems.

I was working with the following modification of your code above.
```julia
using LinearAlgebra, LinearMaps, SparseArrays, BenchmarkTools

spd = SparseMatrixCSC{ComplexF64}(I, 1000, 1000)
A = ones(2, 2)
x = ones(2000)
B  = kron(spd, A)
Bi = kron(spd, im*A)
Blm  = kron(LinearMap(I, 1000), LinearMap(A))
Blmi = kron(LinearMap(I, 1000), LinearMap(im*A))
Blmii = kron(LinearMap(I, 1000), im*LinearMap(A))
Blmiii = kron(LinearMap(I, 1000), FillMap(float(im), (2, 2)))
Blmiiii = kron(spd, im*LinearMap(A))
Blmiiiii = im*kron(spd, LinearMap(A))

begin
    @btime $B * $x;
    @btime $Bi * $x;
    @btime $Blm * $x;
    @btime $Blmi * $x;
    @btime $Blmii * $x;
    @btime $Blmiii * $x;
    @btime $Blmiiii * $x;
    @btime $Blmiiiii * $x;
end
```
The results are as follows:
```julia
  7.236 μs (2 allocations: 31.33 KiB)
  7.471 μs (2 allocations: 31.33 KiB)
  3.870 μs (6 allocations: 15.95 KiB)
  5.238 μs (10 allocations: 31.63 KiB) # for this you should not promote x to complex
  26.870 μs (13 allocations: 31.86 KiB) # this is the cost of the generic mul-code!
  10.409 μs (6 allocations: 31.52 KiB)
  13.292 μs (8 allocations: 47.34 KiB)
  13.403 μs (8 allocations: 47.34 KiB)
```
As you can see, it may pay off to first multiply `im*A` and then call `LinearMap`, or else you're running into the generic matvec problem, which cannot be resolved on the `LinearMaps.jl`'s end. As an alternative, you can see that the FillMap approach is not bad, and certainly using the `LinearMap(I, 1000)` approach is superior over `spd`. It may even make a difference if you use `im` or `float(im)`, so I'd recommend benchmarking first to avoid hard to debug conversion issues and generic fallbacks.
