### ISSUE TITLE
Missing method mul!(::Matrix,::Matrix,::LinearMap)

### ISSUE THREAD

**Issue by david-pl** [Jutho/LinearMaps.jl#129]
Hi,

It seems like the method for in-place multiplication where the final argument is a `LinearMap` is missing:
```julia
using LinearMaps, LinearAlgebra
N = 10
l = LinearMap(identity, N)
A = rand(N,N)

B = similar(A)
mul!(B, l, A) # works in this order
mul!(B, A, l) # MethodError
```

I'm on Julia v1.5.3 and LinearMaps v3.1.0.

**Comment by dkarrasch** [comment]
Thanks for your report. I have something working, but comparing with our existing left-multiplication by transpose/adjoint matrices, it's not so clear what should be actually done:

1. compute the columns of `l` iteratively and multiply them by `A`, or
2. compute `mul!(B, A, l)` as `mul!(transpose(B), transpose(l), transpose(A))` as in `left.jl`?

The second option is generally beneficial because it avoids computing the columns of the linear map (and allocating an intermediate vector for that), but it doesn't work for your example because the transpose is not defined. Should we handle that by `try`-`catch`? Any opinions?

**Comment by david-pl** [comment]
Thanks for the quick reply!

I just wrote this code as an MWE. In my actual use-case I have an `fc` defined, so I'd definitely go with option 2.

Also, I'm not sure, but wouldn't it be possible to handle the case where the transpose is not defined by a dispatch instead of `try-catch`? Something like
```julia
mul!(Y,X,L::FunctionMap{T,F,<:Nothing}) where {T,F} = option-1
mul!(Y,X,L::FunctionMap{T,F,FC}) where {T,F,FC} = option-2
```
Are there any other `LinearMaps` where the transpose could be undefined?

**Comment by dkarrasch** [comment]
Well, `L` could be an involved `LinearMap` (like a `LinearCombination`), where some FunctionMap with undefined adjoint is burried somewhere deep.

**Comment by dkarrasch** [comment]
Hm, the try-catch-block is also suboptimal, because it may take a while to get to the point of error. In an iterative procedure, you would bump into the try-wall at every step. So I guess if anything than we should hard-code the adjoint-route, and let it fail when there is no adjoint/transpose defined.

**Comment by david-pl** [comment]
I was just thinking the same thing. I guess it's fine for the method to actually error in that case. After all, the function for this kind of multiplication simply wasn't provided when defining `l` here. It just feels slightly inconsistent since `A*l` works, but I'd still go for this option.
