### ISSUE TITLE
Issue with transpose map

### ISSUE THREAD

**Issue by andreasvarga** [Jutho/LinearMaps.jl#157]
I am about to finish the transition of operators defined in the [MatrixEquations.jl](https://github.com/andreasvarga/MatrixEquations.jl) package from `LinearOperators`- to `LinearMaps`-based implementation. In most cases I managed the definition of transpose/adjoint maps at the data level (simply using transposed arrays in the definitions of linear maps). However, this does not work for a more involved map which describes a Sylvester system of matrix equations of the form `M: (X,Y) -> (AX+YB, CX+YD )`, where `(A,C)` and `(B,D)` are pairs of square matrices. The transpose mapping is  `MT: (X,Y) -> (A'X+C'Y, XB'+YD' )` and has a different form. Therefore I implemented a separate` mul! `for the transpose map. The basic things  are working well as can be seen below:

```
julia> Tr
8×8 SylvesterSystemMap{Int64}

julia> Trt = Tr'
8×8 LinearMaps.TransposeMap{Int64} of
  8×8 SylvesterSystemMap{Int64}

julia> x = rand(8);

julia> Tr*x;

julia> Trt*x;

```
However, I am getting an error when I am trying to convert the transpose map `Trt` to a matrix:
```
julia> Matrix(Tr)
8×8 Matrix{Int64}:
 1  0  0  0  11   0  21   0
 0  1  0  0   0  11   0  21
 0  0  1  0  12   0  22   0
 0  0  0  1   0  12   0  22
 1  0  0  0   1   0   0   0
 0  1  0  0   0   1   0   0
 0  0  1  0   0   0   1   0
 0  0  0  1   0   0   0   1

julia> Matrix(Trt')  # transpose of transpose is the original maping
8×8 Matrix{Int64}:
 1  0  0  0  11   0  21   0
 0  1  0  0   0  11   0  21
 0  0  1  0  12   0  22   0
 0  0  0  1   0  12   0  22
 1  0  0  0   1   0   0   0
 0  1  0  0   0   1   0   0
 0  0  1  0   0   0   1   0
 0  0  0  1   0   0   0   1

julia> Matrix(Trt)
ERROR: transpose not implemented for 8×8 SylvesterSystemMap{Int64}
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] _unsafe_mul!(y::SubArray{Int64, 1, Matrix{Int64}, Tuple{Base.Slice{Base.OneTo{Int64}}, Int64}, true}, A::LinearMaps.TransposeMap{Int64, SylvesterSystemMap{Int64}}, x::Vector{Int64})
   @ LinearMaps ~\.julia\packages\LinearMaps\r6i00\src\transpose.jl:53
 [3] Matrix{Int64}(A::LinearMaps.TransposeMap{Int64, SylvesterSystemMap{Int64}})
   @ LinearMaps ~\.julia\packages\LinearMaps\r6i00\src\conversion.jl:8
 [4] (Matrix{T} where T)(A::LinearMaps.TransposeMap{Int64, SylvesterSystemMap{Int64}})
   @ LinearMaps ~\.julia\packages\LinearMaps\r6i00\src\conversion.jl:13
 [5] top-level scope
   @ REPL[36]:1

```

The error occurs in 
```
_unsafe_mul!(y::AbstractVecOrMat, A::TransposeMap, x::AbstractVector) =
    issymmetric(A.lmap) ?
        _unsafe_mul!(y, A.lmap, x) : error("transpose not implemented for $(A.lmap)")
```
I would appreciate your advice to manage this issue.

**Comment by andreasvarga** [comment]
In the meantime I managed by implementing a custom `Base.Matrix` based on the defined `mul!`:
```
function Base.Matrix{T}(A::LinearMaps.TransposeMap{T, SylvesterSystemMap{T}}) where {T}
   M, N = size(A)
   mat = Matrix{T}(undef, (M, N))
   v = fill(zero(T), N)
   @inbounds for i in 1:N
       v[i] = one(T)
       mul!(view(mat, :, i), A, v)
       v[i] = zero(T)
   end
   return mat
end
```
I wonder if this is the only way to obtain the following results:
```
julia> Matrix(Trt)
8×8 Matrix{Int64}:
  1   0   0   0  1  0  0  0
  0   1   0   0  0  1  0  0
  0   0   1   0  0  0  1  0
  0   0   0   1  0  0  0  1
 11   0  12   0  1  0  0  0
  0  11   0  12  0  1  0  0
 21   0  22   0  0  0  1  0
  0  21   0  22  0  0  0  1

julia> Matrix(Trt)'-Matrix(Tr)
8×8 Matrix{Int64}:
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
```

**Comment by andreasvarga** [comment]
I think I can live with the above solution. So, I am closing this issue. Thanks for your time.

**Comment by dkarrasch** [comment]
Sorry, my mail didn't seem to update for a few days and I didn't get the notification. You should not need your own copy of the `Matrix` function, and I wouldn't recommend that. There's an underlying issue which should be fixed: we use the internal `_unsafe_mul!` in the generic `Matrix` function, which gets caughted by the method you were pointing to, instead of https://github.com/Jutho/LinearMaps.jl/blob/f956c00eb9a9927dd76f0a24d00109965ae1e562/src/LinearMaps.jl#L234 because that one is more generic.

There are two possible options:

1. You could change your implementations from overloading `LinearAlgebra.mul!` to `LinearMaps._unsafe_mul!`. If we want this, we should recommend and emphasize that this is the way to write custom map types in the docs. This would go along with removing all size checks, because this is then taken care of by `LinearMaps.jl`.
2. We use `mul!` instead of the internal `_unsafe_mul!` in the generic `Matrix` function, which would, however, check size compatibility at every column vector. This is unlikely a bottleneck in the computations anyway.

I have some sympathy for the first action, because it keeps the nice distinction between pure multiplication code and safety checks also for users with custom map types. OTOH, it adds a bit to the mental load. Users who prefer to overload `LinearAlgebra.mul!` will keep running into the same issue as you did.

Opinions, wishes, recommendations?

**Comment by andreasvarga** [comment]
I use the conversion to Matrix form, to have a feeling of the structure of the matrix associated to a the linear map. However, this function is only for convenience purposes and is not essential for the main functionality of LM. Therefore, some extra checks for dimensions are tolerable and lead to no performance degradation of the main functionality. So, my preference would be solution 2.

**Comment by dkarrasch** [comment]
I think you're right. The `Matrix` conversion does not belong to the performance part, but to the convenience part of the package. And in fact, we have here

https://github.com/Jutho/LinearMaps.jl/blob/f956c00eb9a9927dd76f0a24d00109965ae1e562/src/LinearMaps.jl#L112-L115

also `mul!` even though we've checked compatibility before, and IIRC, that's for the same reason.
