### ISSUE TITLE
Upgrade to 0.7

### ISSUE THREAD

**Issue by haampie** [Jutho/LinearMaps.jl#22]
Since IterativeSolvers.jl advocates LinearMaps and is upgrading to Julia 0.7, could LinearMaps be updated as well?

**Comment by dkarrasch** [comment]
Short update: I went through all `src` files. First, I have all my modified files in a Julia 0.7 `dev` folder, so compiling and testing works. I'm not sure how to submit these files now as a WIP-PR... Do I need to fork the package first, create a branch and submit as PR? How would I connect my `dev` folder to the branch?

The switch from `At_mul_B!` and alike to simply `mul!` turns out to be rather challenging, but maybe I have taken the wrong design route. Before, `transpose` and `adjoint` wrapped whatever `LinearMap` it got into a `TransposeMap` or `AdjointMap` object. For these, `==` was defined and `isposdef` builds on it. The call to some `Ax_mul_B!` always "went down in the hierarchy" of WrappedMaps. Now, when we implement `At_mul_B!` by something like `mul!(y,transpose(A.lmap),x)`, emulating the `LinearAlgebra` behavior, we don't reduce the level in the hierarchy, unless we specify `transpose` of `FunctionMap`, `WrappedMap` as a `FunctionMap` and `WrappedMap`, respectively. That's what I currently have, but that breaks all `==` and therefore `isposdef`, for instance. It also doesn't allow for test on `isposdef(transpose(F)*F)` for a `FunctionMap` `F` that doesn't have an `fc` field. That may be a minor issue because if `F` doesn't have a transpose, then we can't work with `transpose(F)*F` anyway, yet it was supposed to give `true`.

Any ideas?

**Comment by dkarrasch** [comment]
Another option that came to my mind is to have an exported `mul!(y,A::LinearMap,x)` interface in `LinearMaps.jl`, which dispatches on `LinearAlgebra`s one, and that calls `A_mul_B!` and alike internally, which are then no longer inherited from somewhere else. This way we might only need to drop `Base.` in front of the vector multiplication functions.

**Comment by Jutho** [comment]
Thanks for looking into this; indeed I see your point and some nontrivial design questions follow. 

Maybe not all of the functionality is really used / relied upon, like the conjugation trick to do `At_mul_B!` on an `AdjointMap`. Not sure how many people were relying on this behaviour.

The basic adjoint behaviour should of course work, and for this, you also point out some problems. I'll try to look at it asap (next week?), but I am open to any suggestion/solution.

**Comment by dkarrasch** [comment]
I think that generally all functionality is needed. In linear combinations and compositions, and combinations thereof, one may encounter all sorts of `Ax_mul_B!` calls, and I think some are even tested. Since all types defined are subtypes of `LinearMap`, having one `LinearAlgebra.mul!(y,::LinearMap,x)` defined suffices. This could call `A_mul_B!` on the argument, which may then call  `At_mul_B!` or whatever needed. If there is a naming conflict with the old `Base.A_mul_B!` etc. we could prepend an underscore. Again, not dispatching `mul!` on each subtype individually should be of no harm, still calls like `mul!(y,transpose(A),x)` emulating the Julia 0.7 behavior should work fine. Some of `A_mul_B!` functions in turn call `*(A.lmap, x)`, which should call `mul!`, which calls `A_mul_B!(y,A.lmap,x)`, which takes us down in the hierarchy. My wrong design route was to redefine all `A_mul_B!` instances by multiple dispatches on `mul!` and calling `transpose` or `adjoint` on the argument, which does not go down in the hierarchy. This way, we would not need to define generic instances of `Ax_mul_B!(y,A::LinearMap,x)`, but only for the specific types.

I'll try to work on it on Friday.

**Comment by dkarrasch** [comment]
Tests pass!!! I proceeded as described above. One minor beauty deficiency is that I had to redefine the `A_mul_B(!)` family for matrices. At the very end of the hierarchy, we end up with matrices, and their matvec multiplication is called with `A_mul_B!` just as while we walked through the wrapping hierarchy. But all of this is not exported and invisible, the only external interface is the `LinearAlgebra.mul!` and `Base.*` dispatch. Back to the original `IterativeSolvers.jl` question: calls to `A_mul_B!` on LinearMaps should be changed to `mul!` consistent with general Julia once this is finalized and merged.

Now, how do I get the files from my Julia_0.7/dev folder here on github? I tried directly via Juno, but it tells me I don't have the rights to push a branch.

**Comment by Jutho** [comment]
The typical approach is indeed to fork a personal copy of this whole repository, push the changes there (either on a new branch or directly on the master branch), and then the github web interface will automatically offer you the option to transform this into a pull requests onto this repository.

**Comment by dkarrasch** [comment]
Do we need to tag the new version, so that the package managers don't get confused?

Otherwise, this issue is resolved, @haampie.

As for not importing the Base operations, `+` and `*` etc., I can't get it to work with the import even after rectifying the product in `WrappedMap.jl`. During the tests, it keeps complaining
```
MethodError: no method matching *(::Array{Complex{Float64},2}, ::Array{Complex{Float64},1})
  You may have intended to import Base.*
```
so when I do import `Base.*` everything works as usual again. For consistency, we may add a qualifier in the WrappedMap later, but currently I don't see how to get rid of the operations import, which is not too bad probably.

**Comment by Jutho** [comment]
Strange, it works for me. I'll push another commit soon with a few minor things and then I'll tag a new version.

**Comment by Jutho** [comment]
Ah, no, it does not.

**Comment by Jutho** [comment]
There was another one, line 71 in linearcombination.jl

**Comment by Jutho** [comment]
Could you check if everything works for you if you checkout master

**Comment by dkarrasch** [comment]
How do I checkout master on the console? I tried `dev LinearMaps#master` in Pkg-mode, but it tells me `Path `/Users/karrasch/.julia/dev/LinearMaps` exists and looks like the correct package, using existing path instead of cloning`, so I'm not sure it actually downloaded the master-branch.

**Comment by dkarrasch** [comment]
Tests pass! Good catches.

**Comment by Jutho** [comment]
New version tagged (awaiting METADATA merge), so I think this can be closed.
