### ISSUE TITLE
LinearMaps with UniformScaling

### ISSUE THREAD

**Issue by ewskau** [Jutho/LinearMaps.jl#36]
Is there any reason that a linear map shouldn't work with a UniformScaling from the LinearAlgebra package? Something like:
```
Base.:(*)(A::LinearMap, α::UniformScaling) = *(α.λ, A)
Base.:(*)(α::UniformScaling, A::LinearMap) = *(α.λ, A)
Base.:(*)(A::LinearMaps.LinearCombination, α::UniformScaling) = *(α.λ, A)
Base.:(*)(α::UniformScaling, A::LinearMaps.LinearCombination) = *(α.λ, A)
```
I find this useful, but perhaps there is a reason it is not already done?

**Comment by dkarrasch** [comment]
I think we could add it. There has been, however, some concern about non-commutative eltypes in Julia Base/LinearAlgebra, so I think we should be more careful here as well. So, `A * α` should be something like `A * (α * IdentityMap(size(A, 2)))`, or so? The same holds for

https://github.com/Jutho/LinearMaps.jl/blob/73bec0d7f9046c0f3645deb2264d48a63f1be3b6/src/linearcombination.jl#L70

etc.

**Comment by dkarrasch** [comment]
That's right. The classic test case is choosing the quaternions as the field, and when/if we make such a change, we will need to incorporate that for testing. I'd like to have @Jutho's opinion on that first, and I can make the necessary modifications then after the holidays. 🎄 🎅

**Comment by Jutho** [comment]
Yes it is probably good to aim for full compatibility with non-commutative number types. It has never been on my priority list, but the approach outlined here sounds good. I guess the `LinearCombination` type could then be simplified to only store linear maps, no more scalar coeffs.

**Comment by dkarrasch** [comment]
This sounds like an exciting project. I'd say that the `LinearCombination` type must be simplified as you say. We will need, however, a `UniformScalingMap` type instead, in order to be able to represent `α * IdentityMap(size(A, 2))`. Currently, this would produce a `LinearCombination` object with `α` as a coefficient. I wonder if we need the `IdentityMap` type then, or if we could re-dedicate it to a "`ScaledIdentityMap`" (or `UniformScalingMap`)? I can't think of another use case for `IdentityMap`s.
