### ISSUE TITLE
Potential reasons why Quaternion and Octonion tests fail

### ISSUE THREAD

**Issue by yikait2** [Jutho/LinearMaps.jl#42]
In the last test in the runtest.jl, which involves Quaternion tests, I found the following code fail:
 @test (α * L')' * x ≈ (α * A')' * x 

By running separate tests, I found two issues about this code:
1. The ≈ symbol is not yet defined for quaternion and octonion matrices, the reason of which might be the "norm" of a quaternion matrix is not defined.
2. There might be an adjoint matrix multiplication problem(might be At_mul_B!) since the conjugate defined by quaternions and Octonions are different from normal complex numbers. This can be implied by the tests that (y=(α * L')') == LinearMap(y'=(α * A')' ) and y*x==y'*x (since the two tests use mult defined in LinearMaps.jl instead of the one in transpose.jl), but at the same time test (α * L')' * x and (α * A')' * x have drastic difference in the imaginary part.

The same issues result in the failure of all four test, the previous and the following three:
@test (α * L')' * v ≈ (α * A')' * v
@test Array(@inferred adjoint(α * L * β)) ≈ conj(β) * A' * conj(α)
@test Array(@inferred transpose(α * L * β)) ≈ β * transpose(A) * α

**Comment by dkarrasch** [comment]
Our previous Quaternion tests fail only on Julia v1.2, and the reason is a change in the definition of `norm` on Julia master. It now involves a call to `float`, which is the missing method for `Quaternion`s and `Octonion`s. I have prepared a PR at `Quaternions.jl`: https://github.com/JuliaGeometry/Quaternions.jl/pull/31 to fix this. Defining a norm method for Quaternions/Octonions seems like type piracy, so I'd prefer that we fix issues upstream whenever possible. I'll try to see what is happening with Octonion.

**Comment by dkarrasch** [comment]
@yikait2 Thanks for the interesting question and the lesson I learned. 😃 It turns out that octonions are not associative, as you say in the section header of the new tests. That means, however, that the following already fails:
```
m = 1
x = Octonion.(rand(m), rand(m), rand(m), rand(m), rand(m), rand(m), rand(m), rand(m)) # vector
A = Octonion.(rand(m,m), rand(m,m), rand(m,m), rand(m,m), rand(m,m), rand(m,m), rand(m,m), rand(m,m)) # matrix
α = Octonion.(rand(8)...) # scalar
α * A * x == α * (A * x) # false
α * A * x == (α * A) * x # true
```
That means, without brackets, multiplication is applied "from left to right". When `A` is a `LinearMap`, then `α * A` is a `CompositeMap`. Multiplication of a vector with a `CompositeMap`, however, is performed "from right to left", which is necessary, because we want to use only matrix-vector-multiplication and would need to know how to multiply matrices/`LinearMap`s otherwise, which we don't assume is known. For that reason, your issue clarifies that we really need an associative multiplication for that package, but otherwise I'm not sure anything can be done for non-associative number types. Well, composition of maps needs to be used very carefully with non-associative number types.

**Comment by dkarrasch** [comment]
I'm closing this since all tests pass, except for the new Octonion tests on Julia v1.2+, which require a `float` method which was forgotten in a recent `Quaternions.jl` update. This is going to be fixed sooner or later. Working with `LinearMaps.jl` and `Octonions` is not really recommended by the nonassociativeness of multiplication, which makes it really hard to predict in composite (adjoint/transpose) linear maps which numbers are multiplied in which order.
