### ISSUE TITLE
Allocation-free 5-arg mul! for custom maps

### ISSUE THREAD

**Issue by jagot** [Jutho/LinearMaps.jl#75]
This is basically a follow-up to https://github.com/Jutho/LinearMaps.jl/issues/56;

If I have a custom type for which I have a defined a allocation-free 5-arg `mul!`
```julia
struct MyIntegralOperator{T} <: LinearMap{T}
...
end

mul!(y, A::MyIntegralOperator, x, α=true, β=false) = ...
```
which I want to form linear combinations of, how do I get allocation-free application? Right now, I think I need to duplicate the following functions, since it is not possible for types outside of LinearMaps.jl to belong to `FreeMap`:

https://github.com/Jutho/LinearMaps.jl/blob/95cc89cffff4b980af41aea32483af739a2d168c/src/linearcombination.jl#L83-L93

and

https://github.com/Jutho/LinearMaps.jl/blob/95cc89cffff4b980af41aea32483af739a2d168c/src/linearcombination.jl#L113-L138

A possible approach could be to tag the `LinearCombination` object with a trait, i.e. a type parameter  (e.g. `MulStyle`) that indicates which method to dispatch to. Then the user would only need to overload `mulstyle(::MyIntegralOperator) = FiveArgs`. This pattern has been used to great effect in e.g. https://github.com/JuliaArrays/LazyArrays.jl/blob/db8b20746c26873d635df18bcaac06382def11bb/src/linalg/muladd.jl

**Comment by dkarrasch** [comment]
That sounds like a good idea. So, basically, at construction of a `LinearCombination` object, check whether all summands have the `FiveArgs` mulstyle, and in that case assign that mulstyle to the `LinearCombinations` object, right?

**Comment by jagot** [comment]
Yes, although in practice, I would normally construct a `LinearCombination` by successively adding new terms, so then only the `MulStyle` of the new term need be compared with that of the `LinearCombination`.

**Comment by dkarrasch** [comment]
@jagot I implemented your suggestion and I'd be happy if you could review it.

I realized that this is a very neat way of perhaps avoiding this nasty `VERSION` distinction (almost) altogether. The point is that depending on whether old or new `mul!` is available, matrices will get the `FiveArg` or `ThreeArg` trait. But otherwise, the dispatch and the underlying multiplication code for `LinearCombinations` are just the same.

@Jutho If you find the time for review, I'd say this has highest priority. The next one is #72. 😉
